# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lib/grpc/tesrpc/rpc.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lib/grpc/tesrpc/rpc.proto',
  package='tesrpc',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19lib/grpc/tesrpc/rpc.proto\x12\x06tesrpc\"\x1c\n\x0cTestResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x1b\n\x0bTestRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"s\n\x14GetTaskNoticeRequest\x12\x13\n\x0bwarehouseID\x18\x01 \x01(\t\x12\x12\n\nclientCode\x18\x02 \x01(\t\x12\x11\n\ttokenCode\x18\x03 \x01(\t\x12\x0e\n\x06topics\x18\x04 \x01(\t\x12\x0f\n\x07msgType\x18\x05 \x01(\t\"%\n\x15GetTaskNoticeResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"X\n\x1cGetConveyorDataReportRequest\x12\x13\n\x0bwarehouseID\x18\x01 \x01(\t\x12\x12\n\nclientCode\x18\x02 \x01(\t\x12\x0f\n\x07msgType\x18\x03 \x01(\t\"-\n\x1dGetConveyorDataReportResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2\x85\x02\n\x06TesRpc\x12;\n\nTestStream\x12\x13.tesrpc.TestRequest\x1a\x14.tesrpc.TestResponse\"\x00\x30\x01\x12R\n\rGetTaskNotice\x12\x1c.tesrpc.GetTaskNoticeRequest\x1a\x1d.tesrpc.GetTaskNoticeResponse\"\x00(\x01\x30\x01\x12j\n\x15GetConveyorDataReport\x12$.tesrpc.GetConveyorDataReportRequest\x1a%.tesrpc.GetConveyorDataReportResponse\"\x00(\x01\x30\x01\x62\x06proto3'
)




_TESTRESPONSE = _descriptor.Descriptor(
  name='TestResponse',
  full_name='tesrpc.TestResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='tesrpc.TestResponse.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=65,
)


_TESTREQUEST = _descriptor.Descriptor(
  name='TestRequest',
  full_name='tesrpc.TestRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='tesrpc.TestRequest.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=94,
)


_GETTASKNOTICEREQUEST = _descriptor.Descriptor(
  name='GetTaskNoticeRequest',
  full_name='tesrpc.GetTaskNoticeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='warehouseID', full_name='tesrpc.GetTaskNoticeRequest.warehouseID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clientCode', full_name='tesrpc.GetTaskNoticeRequest.clientCode', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tokenCode', full_name='tesrpc.GetTaskNoticeRequest.tokenCode', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='topics', full_name='tesrpc.GetTaskNoticeRequest.topics', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msgType', full_name='tesrpc.GetTaskNoticeRequest.msgType', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=211,
)


_GETTASKNOTICERESPONSE = _descriptor.Descriptor(
  name='GetTaskNoticeResponse',
  full_name='tesrpc.GetTaskNoticeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='tesrpc.GetTaskNoticeResponse.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=250,
)


_GETCONVEYORDATAREPORTREQUEST = _descriptor.Descriptor(
  name='GetConveyorDataReportRequest',
  full_name='tesrpc.GetConveyorDataReportRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='warehouseID', full_name='tesrpc.GetConveyorDataReportRequest.warehouseID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clientCode', full_name='tesrpc.GetConveyorDataReportRequest.clientCode', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msgType', full_name='tesrpc.GetConveyorDataReportRequest.msgType', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=340,
)


_GETCONVEYORDATAREPORTRESPONSE = _descriptor.Descriptor(
  name='GetConveyorDataReportResponse',
  full_name='tesrpc.GetConveyorDataReportResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='tesrpc.GetConveyorDataReportResponse.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=342,
  serialized_end=387,
)

DESCRIPTOR.message_types_by_name['TestResponse'] = _TESTRESPONSE
DESCRIPTOR.message_types_by_name['TestRequest'] = _TESTREQUEST
DESCRIPTOR.message_types_by_name['GetTaskNoticeRequest'] = _GETTASKNOTICEREQUEST
DESCRIPTOR.message_types_by_name['GetTaskNoticeResponse'] = _GETTASKNOTICERESPONSE
DESCRIPTOR.message_types_by_name['GetConveyorDataReportRequest'] = _GETCONVEYORDATAREPORTREQUEST
DESCRIPTOR.message_types_by_name['GetConveyorDataReportResponse'] = _GETCONVEYORDATAREPORTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TestResponse = _reflection.GeneratedProtocolMessageType('TestResponse', (_message.Message,), {
  'DESCRIPTOR' : _TESTRESPONSE,
  '__module__' : 'lib.grpc.tesrpc.rpc_pb2'
  # @@protoc_insertion_point(class_scope:tesrpc.TestResponse)
  })
_sym_db.RegisterMessage(TestResponse)

TestRequest = _reflection.GeneratedProtocolMessageType('TestRequest', (_message.Message,), {
  'DESCRIPTOR' : _TESTREQUEST,
  '__module__' : 'lib.grpc.tesrpc.rpc_pb2'
  # @@protoc_insertion_point(class_scope:tesrpc.TestRequest)
  })
_sym_db.RegisterMessage(TestRequest)

GetTaskNoticeRequest = _reflection.GeneratedProtocolMessageType('GetTaskNoticeRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETTASKNOTICEREQUEST,
  '__module__' : 'lib.grpc.tesrpc.rpc_pb2'
  # @@protoc_insertion_point(class_scope:tesrpc.GetTaskNoticeRequest)
  })
_sym_db.RegisterMessage(GetTaskNoticeRequest)

GetTaskNoticeResponse = _reflection.GeneratedProtocolMessageType('GetTaskNoticeResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETTASKNOTICERESPONSE,
  '__module__' : 'lib.grpc.tesrpc.rpc_pb2'
  # @@protoc_insertion_point(class_scope:tesrpc.GetTaskNoticeResponse)
  })
_sym_db.RegisterMessage(GetTaskNoticeResponse)

GetConveyorDataReportRequest = _reflection.GeneratedProtocolMessageType('GetConveyorDataReportRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETCONVEYORDATAREPORTREQUEST,
  '__module__' : 'lib.grpc.tesrpc.rpc_pb2'
  # @@protoc_insertion_point(class_scope:tesrpc.GetConveyorDataReportRequest)
  })
_sym_db.RegisterMessage(GetConveyorDataReportRequest)

GetConveyorDataReportResponse = _reflection.GeneratedProtocolMessageType('GetConveyorDataReportResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETCONVEYORDATAREPORTRESPONSE,
  '__module__' : 'lib.grpc.tesrpc.rpc_pb2'
  # @@protoc_insertion_point(class_scope:tesrpc.GetConveyorDataReportResponse)
  })
_sym_db.RegisterMessage(GetConveyorDataReportResponse)



_TESRPC = _descriptor.ServiceDescriptor(
  name='TesRpc',
  full_name='tesrpc.TesRpc',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=390,
  serialized_end=651,
  methods=[
  _descriptor.MethodDescriptor(
    name='TestStream',
    full_name='tesrpc.TesRpc.TestStream',
    index=0,
    containing_service=None,
    input_type=_TESTREQUEST,
    output_type=_TESTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetTaskNotice',
    full_name='tesrpc.TesRpc.GetTaskNotice',
    index=1,
    containing_service=None,
    input_type=_GETTASKNOTICEREQUEST,
    output_type=_GETTASKNOTICERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetConveyorDataReport',
    full_name='tesrpc.TesRpc.GetConveyorDataReport',
    index=2,
    containing_service=None,
    input_type=_GETCONVEYORDATAREPORTREQUEST,
    output_type=_GETCONVEYORDATAREPORTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TESRPC)

DESCRIPTOR.services_by_name['TesRpc'] = _TESRPC

# @@protoc_insertion_point(module_scope)
