# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='response.proto',
  package='invtransaction',
  syntax='proto3',
  serialized_options=b'\n+com.megvii.lbg.wes.invtransaction.workorderP\001ZLgit-pd.megvii-inc.com/slg-service/frworkstation/internal/grpc/invtransaction',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eresponse.proto\x12\x0einvtransaction\x1a\x19google/protobuf/any.proto\"r\n\x0e\x43ommonResponse\x12\x12\n\nreturnCode\x18\x01 \x01(\x05\x12\x11\n\treturnMsg\x18\x02 \x01(\t\x12\x15\n\rreturnUserMsg\x18\x03 \x01(\t\x12\"\n\x04\x64\x61te\x18\x04 \x03(\x0b\x32\x14.google.protobuf.AnyB}\n+com.megvii.lbg.wes.invtransaction.workorderP\x01ZLgit-pd.megvii-inc.com/slg-service/frworkstation/internal/grpc/invtransactionb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_COMMONRESPONSE = _descriptor.Descriptor(
  name='CommonResponse',
  full_name='invtransaction.CommonResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='returnCode', full_name='invtransaction.CommonResponse.returnCode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='returnMsg', full_name='invtransaction.CommonResponse.returnMsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='returnUserMsg', full_name='invtransaction.CommonResponse.returnUserMsg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date', full_name='invtransaction.CommonResponse.date', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=175,
)

_COMMONRESPONSE.fields_by_name['date'].message_type = google_dot_protobuf_dot_any__pb2._ANY
DESCRIPTOR.message_types_by_name['CommonResponse'] = _COMMONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CommonResponse = _reflection.GeneratedProtocolMessageType('CommonResponse', (_message.Message,), {
  'DESCRIPTOR' : _COMMONRESPONSE,
  '__module__' : 'response_pb2'
  # @@protoc_insertion_point(class_scope:invtransaction.CommonResponse)
  })
_sym_db.RegisterMessage(CommonResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
