# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VarianceOrderService.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import response_pb2 as response__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='VarianceOrderService.proto',
  package='invtransaction',
  syntax='proto3',
  serialized_options=b'\n*com.megvii.lbg.wes.invtransaction.varianceP\001ZLgit-pd.megvii-inc.com/slg-service/frworkstation/internal/grpc/invtransaction',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1aVarianceOrderService.proto\x12\x0einvtransaction\x1a\x0eresponse.proto\"n\n\x1aVarianceOrderHandleRequest\x12\x15\n\rwarehouseCode\x18\x01 \x01(\t\x12\x0c\n\x04woNo\x18\x02 \x01(\t\x12\x0f\n\x07station\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\x05\x12\x0c\n\x04user\x18\x05 \x01(\t\"a\n\x1bVarianceOrderConfirmRequest\x12\x15\n\rwarehouseCode\x18\x01 \x01(\t\x12\x0c\n\x04woNo\x18\x02 \x01(\t\x12\x0f\n\x07station\x18\x03 \x01(\t\x12\x0c\n\x04user\x18\x04 \x01(\t\"\xc0\x02\n\x1a\x43reateVarianceOrderRequest\x12\x15\n\rwarehouseCode\x18\x01 \x01(\t\x12\x12\n\nvarianceNo\x18\x02 \x01(\t\x12\x0c\n\x04woNo\x18\x03 \x01(\t\x12\x0e\n\x06woType\x18\x04 \x01(\x05\x12\x0e\n\x06reason\x18\x05 \x01(\x05\x12\x12\n\nregionCode\x18\x06 \x01(\t\x12\x0b\n\x03loc\x18\x07 \x01(\t\x12\x19\n\x11\x63ontainerSerialNo\x18\x08 \x01(\x03\x12\x15\n\rcontainerCode\x18\t \x01(\t\x12\x0f\n\x07skuCode\x18\n \x01(\t\x12\x0f\n\x07skuName\x18\x0b \x01(\t\x12\x0b\n\x03lot\x18\x0c \x01(\t\x12\r\n\x05grade\x18\r \x01(\x05\x12\x0b\n\x03qty\x18\x0e \x01(\x05\x12\x0f\n\x07station\x18\x0f \x01(\t\x12\x0c\n\x04rfid\x18\x10 \x03(\t\x12\x0c\n\x04user\x18\x11 \x01(\t2\xc7\x02\n\x14VarianceOrderService\x12\x63\n\x13VarianceOrderCreate\x12*.invtransaction.CreateVarianceOrderRequest\x1a\x1e.invtransaction.CommonResponse\"\x00\x12\x65\n\x14VarianceOrderConfirm\x12+.invtransaction.VarianceOrderConfirmRequest\x1a\x1e.invtransaction.CommonResponse\"\x00\x12\x63\n\x13VarianceOrderHandle\x12*.invtransaction.VarianceOrderHandleRequest\x1a\x1e.invtransaction.CommonResponse\"\x00\x42|\n*com.megvii.lbg.wes.invtransaction.varianceP\x01ZLgit-pd.megvii-inc.com/slg-service/frworkstation/internal/grpc/invtransactionb\x06proto3'
  ,
  dependencies=[response__pb2.DESCRIPTOR,])




_VARIANCEORDERHANDLEREQUEST = _descriptor.Descriptor(
  name='VarianceOrderHandleRequest',
  full_name='invtransaction.VarianceOrderHandleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='warehouseCode', full_name='invtransaction.VarianceOrderHandleRequest.warehouseCode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='woNo', full_name='invtransaction.VarianceOrderHandleRequest.woNo', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='station', full_name='invtransaction.VarianceOrderHandleRequest.station', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='invtransaction.VarianceOrderHandleRequest.type', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user', full_name='invtransaction.VarianceOrderHandleRequest.user', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=172,
)


_VARIANCEORDERCONFIRMREQUEST = _descriptor.Descriptor(
  name='VarianceOrderConfirmRequest',
  full_name='invtransaction.VarianceOrderConfirmRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='warehouseCode', full_name='invtransaction.VarianceOrderConfirmRequest.warehouseCode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='woNo', full_name='invtransaction.VarianceOrderConfirmRequest.woNo', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='station', full_name='invtransaction.VarianceOrderConfirmRequest.station', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user', full_name='invtransaction.VarianceOrderConfirmRequest.user', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=271,
)


_CREATEVARIANCEORDERREQUEST = _descriptor.Descriptor(
  name='CreateVarianceOrderRequest',
  full_name='invtransaction.CreateVarianceOrderRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='warehouseCode', full_name='invtransaction.CreateVarianceOrderRequest.warehouseCode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='varianceNo', full_name='invtransaction.CreateVarianceOrderRequest.varianceNo', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='woNo', full_name='invtransaction.CreateVarianceOrderRequest.woNo', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='woType', full_name='invtransaction.CreateVarianceOrderRequest.woType', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reason', full_name='invtransaction.CreateVarianceOrderRequest.reason', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='regionCode', full_name='invtransaction.CreateVarianceOrderRequest.regionCode', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='loc', full_name='invtransaction.CreateVarianceOrderRequest.loc', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='containerSerialNo', full_name='invtransaction.CreateVarianceOrderRequest.containerSerialNo', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='containerCode', full_name='invtransaction.CreateVarianceOrderRequest.containerCode', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='skuCode', full_name='invtransaction.CreateVarianceOrderRequest.skuCode', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='skuName', full_name='invtransaction.CreateVarianceOrderRequest.skuName', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lot', full_name='invtransaction.CreateVarianceOrderRequest.lot', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='grade', full_name='invtransaction.CreateVarianceOrderRequest.grade', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='qty', full_name='invtransaction.CreateVarianceOrderRequest.qty', index=13,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='station', full_name='invtransaction.CreateVarianceOrderRequest.station', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rfid', full_name='invtransaction.CreateVarianceOrderRequest.rfid', index=15,
      number=16, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user', full_name='invtransaction.CreateVarianceOrderRequest.user', index=16,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=274,
  serialized_end=594,
)

DESCRIPTOR.message_types_by_name['VarianceOrderHandleRequest'] = _VARIANCEORDERHANDLEREQUEST
DESCRIPTOR.message_types_by_name['VarianceOrderConfirmRequest'] = _VARIANCEORDERCONFIRMREQUEST
DESCRIPTOR.message_types_by_name['CreateVarianceOrderRequest'] = _CREATEVARIANCEORDERREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VarianceOrderHandleRequest = _reflection.GeneratedProtocolMessageType('VarianceOrderHandleRequest', (_message.Message,), {
  'DESCRIPTOR' : _VARIANCEORDERHANDLEREQUEST,
  '__module__' : 'VarianceOrderService_pb2'
  # @@protoc_insertion_point(class_scope:invtransaction.VarianceOrderHandleRequest)
  })
_sym_db.RegisterMessage(VarianceOrderHandleRequest)

VarianceOrderConfirmRequest = _reflection.GeneratedProtocolMessageType('VarianceOrderConfirmRequest', (_message.Message,), {
  'DESCRIPTOR' : _VARIANCEORDERCONFIRMREQUEST,
  '__module__' : 'VarianceOrderService_pb2'
  # @@protoc_insertion_point(class_scope:invtransaction.VarianceOrderConfirmRequest)
  })
_sym_db.RegisterMessage(VarianceOrderConfirmRequest)

CreateVarianceOrderRequest = _reflection.GeneratedProtocolMessageType('CreateVarianceOrderRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEVARIANCEORDERREQUEST,
  '__module__' : 'VarianceOrderService_pb2'
  # @@protoc_insertion_point(class_scope:invtransaction.CreateVarianceOrderRequest)
  })
_sym_db.RegisterMessage(CreateVarianceOrderRequest)


DESCRIPTOR._options = None

_VARIANCEORDERSERVICE = _descriptor.ServiceDescriptor(
  name='VarianceOrderService',
  full_name='invtransaction.VarianceOrderService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=597,
  serialized_end=924,
  methods=[
  _descriptor.MethodDescriptor(
    name='VarianceOrderCreate',
    full_name='invtransaction.VarianceOrderService.VarianceOrderCreate',
    index=0,
    containing_service=None,
    input_type=_CREATEVARIANCEORDERREQUEST,
    output_type=response__pb2._COMMONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='VarianceOrderConfirm',
    full_name='invtransaction.VarianceOrderService.VarianceOrderConfirm',
    index=1,
    containing_service=None,
    input_type=_VARIANCEORDERCONFIRMREQUEST,
    output_type=response__pb2._COMMONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='VarianceOrderHandle',
    full_name='invtransaction.VarianceOrderService.VarianceOrderHandle',
    index=2,
    containing_service=None,
    input_type=_VARIANCEORDERHANDLEREQUEST,
    output_type=response__pb2._COMMONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VARIANCEORDERSERVICE)

DESCRIPTOR.services_by_name['VarianceOrderService'] = _VARIANCEORDERSERVICE

# @@protoc_insertion_point(module_scope)
