# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from  ..common import common_pb2 as common__pb2
from  . import warectu_pb2 as warectu__pb2


class WarectuStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TransferTrigger = channel.unary_unary(
                '/warectu.Warectu/TransferTrigger',
                request_serializer=warectu__pb2.TransferTriggerRequest.SerializeToString,
                response_deserializer=common__pb2.CommonResponse.FromString,
                )
        self.ExchangeChooseStation = channel.unary_unary(
                '/warectu.Warectu/ExchangeChooseStation',
                request_serializer=warectu__pb2.ExchangeChooseStationRequest.SerializeToString,
                response_deserializer=warectu__pb2.ExchangeChooseStationResponse.FromString,
                )


class WarectuServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TransferTrigger(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExchangeChooseStation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WarectuServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TransferTrigger': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferTrigger,
                    request_deserializer=warectu__pb2.TransferTriggerRequest.FromString,
                    response_serializer=common__pb2.CommonResponse.SerializeToString,
            ),
            'ExchangeChooseStation': grpc.unary_unary_rpc_method_handler(
                    servicer.ExchangeChooseStation,
                    request_deserializer=warectu__pb2.ExchangeChooseStationRequest.FromString,
                    response_serializer=warectu__pb2.ExchangeChooseStationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'warectu.Warectu', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Warectu(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TransferTrigger(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/warectu.Warectu/TransferTrigger',
            warectu__pb2.TransferTriggerRequest.SerializeToString,
            common__pb2.CommonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExchangeChooseStation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/warectu.Warectu/ExchangeChooseStation',
            warectu__pb2.ExchangeChooseStationRequest.SerializeToString,
            warectu__pb2.ExchangeChooseStationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
